### ISSUE TITLE
An assumption is made that localhost is being used

### ISSUE THREAD

**Issue by craig8** [VOLTTRON/volttron-installer#9] opened 2023-10-03 18:48 UTC
**Describe the bug**
Clicking on Add a Host Machine produces 404 when not on localhost

![image](https://github.com/VOLTTRON/volttron-installer/assets/3979063/22a82abe-f562-4a02-8712-7d79e09edb7c)

![image](https://github.com/VOLTTRON/volttron-installer/assets/3979063/251a29fb-bc20-4186-b473-05a653dcdf01)

**Comment by dylanwhosthat** [comment] 2023-10-26 18:11
Closing for now as I am unable to reproduce the issue.

**Closed by dylanwhosthat** 2023-10-26 18:11 UTC
Labels: bug
